name: Snyk Code Monitoring

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master  # リポジトリのチェックアウト
      - name: Run Snyk monitor
        uses: snyk/actions/node@master  # SnykのNode.js用アクション
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor