name: AI Code Review for Idempotency

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Read and escape code file
      id: read_code
      run: |
        CODE_CONTENT=$(cat src/index.js | jq -Rs .)
        echo "::set-output name=code::$CODE_CONTENT"

    - name: Log the escaped code
      run: |
        ESCAPED_CODE="${{ steps.read_code.outputs.code }}"
        echo "Escaped code content: ${ESCAPED_CODE}"

    - name: AI-driven Idempotency Check
      run: |
        JSON_PAYLOAD=$(jq -n --arg code "$ESCAPED_CODE" '{
          "model": "gpt-3.5-turbo",
          "prompt": "Please check the following code for idempotency issues: \($code)",
          "max_tokens": 1000
        }')
        echo "Sending JSON Payload: $JSON_PAYLOAD"
        curl -X POST https://api.openai.com/v1/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
        -d "$JSON_PAYLOAD"