name: Hugging Face Code Review

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install -y jq

    - name: Send code to Hugging Face API for analysis
      run: |
        # Read the code content from the file
        CODE_CONTENT=$(cat src/index.js | jq -Rs .)
        
        # Use Fine-grained API token with Read-only access
        curl -X POST https://api-inference.huggingface.co/models/deepcode-sever \
                -H "Authorization: Bearer ${{ secrets.HF_API_KEY }}" \
                -H "Content-Type: application/json" \
                -d "{\"inputs\": $CODE_CONTENT}" \
                -o result.json
        
    - name: Output the analysis results
      run: cat result.json
